### ISSUE TITLE
出现这个错误 [WinError 10053] 你的主机中的软件中止了一个已建立的连接

### ISSUE THREAD

**Issue by fungo1024** [odboy/shadowProxy#1]
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42621)
Traceback (most recent call last):
  File "D:\Program Files\python36\lib\socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\Program Files\python36\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "shadowProxy.py", line 81, in __init__
    BaseHTTPRequestHandler.__init__(self, *args, **kwargs)
  File "D:\Program Files\python36\lib\socketserver.py", line 721, in __init__
    self.handle()
  File "D:\Program Files\python36\lib\http\server.py", line 420, in handle
    self.handle_one_request()
  File "D:\Program Files\python36\lib\http\server.py", line 386, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "D:\Program Files\python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。
----------------------------------------
是因为代理ip不稳定出现网络断开吗？
挂代理访问 shadowproxy 端一直卡着不动，不跳ip 不显示日志。

**Comment by odboy** [comment]
你用的代理IP是经过筛选的没？网上获取的免费代理IP稳定性确实不咋地。  试试用确定可用的代理IP试试呢？

**Comment by fungo1024** [comment]
好的，ip都是这里搞得： http://proxylist.fatezero.org/  
我自己整了一个脚本 筛选 这个项目的ip列表，筛选了响应时间小于0.6秒的，
每次运行 shadowporxy 前 都更新一下 porxylist.txt   

后期看看还有没有质量好点的，ip。。
谢谢师傅的回答！
